### PR TITLE
Friction simulation in gepetto-simulator

### PR DESCRIPTION
**Pull request by proyan**
Adds a friction simulation in the simulator for gepetto.
The friction model is given in https://github.com/proyan/openhrp3-simulator-wo-rtm/blob/0067e5faa4caa3dc8ea73a09d833fd302fcd61cb/hrpGeplib/hrpGepModel/ForwardDynamics.cpp#L69

### CODE REVIEW

**Comment by proyan** [comment]
@andreadelprete With this formulation, the coulomb friction gains that are available from the motor parameters of hrp2-torque-control are quite high. System is unstable with those high gains.

**Comment by proyan** [comment]
@andreadelprete reminder for a review

**Review by andreadelprete — COMMENTED** [review]
I cannot review this code because I don't know it well enough. I took a look and I didn't find any mistake. However, this doesn't mean there is no mistake! :)

**Comment by proyan** [comment]
@olivier-stasse reminder for a review

**Review by olivier-stasse — APPROVED** [review]
I agree with the modifications from an architectural viewpoint. With respect to the correctness of the model,  could you just specify a reference ?

**Comment by proyan** [comment]
The representation of Couloumb and Viscous friction follows [the one from simulink](https://fr.mathworks.com/help/simulink/slref/coulombandviscousfriction.html?requestedDomain=www.mathworks.com). The difference is that the offset and gain parameters for negative and positive input can be different in our case.

**Comment by proyan** [comment]
Merging

**Pull request merged**
